if(NOT INPUT OR NOT OUTPUT OR NOT NAME)
    message(FATAL_ERROR "embed_file.cmake requires -DINPUT= -DOUTPUT= -DNAME=")
endif()

file(READ "${INPUT}" hex HEX)
string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x..,){32})" "\\1\n" bytes "${bytes}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/embed_file.cmake from ${INPUT}. Do not edit.
extern const unsigned char ${NAME}[];
const unsigned char ${NAME}[] = {
${bytes}
};

extern const unsigned ${NAME}_size;
const unsigned ${NAME}_size = sizeof(${NAME});
")
